config/routes.rb
Rails.application.routes.draw do
  devise_for :users, sign_out_via: %i[get post]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :foods, except: %i[edit update]

  resources :recipes, except: %i[edit update] do
    resources :recipe_foods, only: %i[new create destroy]
  end

  # root to: 'foods#index'
  root to: 'recipes#index'
  get '/general_shopping_list', to: 'foods#general'
  get '/public_recipe', to: 'recipes#public'
  # post 'authenticate', to: 'authentication#authenticate'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user, class_name: 'User'
  has_many :recipe_foods, dependent: :destroy, class_name: 'RecipeFood'
  has_many :foods, through: :recipe_foods, class_name: 'Food'

  validates :name, presence: true
  validates :description, presence: true
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:public]

  def index
    @recipes = Recipe.all.includes([:user])
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipe_foods = RecipeFood.includes(%i[recipe food]).where(recipe_id: @recipe.id)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    new_recipe = current_user.recipes.new(recipe_params)

    respond_to do |format|
      format.html do
        if new_recipe.save
          redirect_to '/recipes/', notice: 'Recipe was successfully created.'
        else
          render :new, status: 'Error occured will creating recipe!'
        end
      end
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.delete
    redirect_to '/recipes/', notice: 'Recipe was successfully deleted.'
  end

  def public
    @totals = {}

    @public_recipes = Recipe.where(public: true).includes(:foods, :user).order('created_at DESC')
    @public_recipes.each do |pub|
      total = 0
      RecipeFood.where(recipe_id: pub.id).each do |rec_food|
        total += rec_food.quantity * rec_food.food.price
      end
      @totals[pub.id] = total
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description, :ingredients, :public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<section class="r-form">
  <div class="create">
    <%= form_with model: @recipe do |form| %>
      <%= form.text_field :name, placeholder: 'Recipes name' %>
      <%= form.text_field :preparation_time, placeholder: 'Preparation time' %>
      <%= form.text_field :cooking_time, placeholder: 'Cooking time' %>
      <%= form.text_field :description, placeholder: 'Recipes description' %>
       <div class="my-4">
      <%= form.label :public %><br/>
      <%= form.label :public, "Yes", value: "true" %>
      <%= form.radio_button :public, true, checked: true %> &nbsp; &nbsp;
      <%= form.label :public, "No", value: "false" %>
      <%= form.radio_button :public, false %>
    </div>
        <div class="actions">
          <%= form.submit %>
        </div>
  <% end %>
  </div>
</section>

app/views/recipes/_recipe.html.erb
<div class="recipe-card">
    <div class="recipe_card_img">
    <h3><%= recipe.name %></h3>
        <%=image_tag("Salad.jpg", alt: "Salad")%>
        <%= button_to "Delete Recipe", recipe_path(recipe.id), method: :delete %>
    </div>
    <div class="recipe_card_content">
        <div class="recdata">
        <p><%= recipe.user.name %></p>
        <% if recipe.public %>
            <p>Public</p>
        <% else %>
            <p>Private</p>
        <% end %>
        </div>
    
    <div class="recipe_desc_card">
        <h3 class="Rtitle">Description</h3>
        <p><%= recipe.description %></p>
    </div>
    
    <%= link_to "View Recipe details", recipe_path(recipe.id) %>

    </div>

</div>

app/views/recipes/_recipe_foods.html.erb
<tr>
  <td> <%= recipe_foods.food.name %> </td>
  <td> <%= recipe_foods.quantity %> <%= recipe_foods.food.measurment %> </td>
  <td><%= recipe_foods.food.price * recipe_food.quantity %></td>
  <% if recipe_foods.recipe.user == current_user %>
    <td>
      <%= button_to "Remove", recipe_recipe_foods_path(recipe_foods.recipe_id, recipe_foods.id), method: :delete, data: { confirm: "Are you sure?" } %>
    </td>
  <% end %>
</tr>

app/views/recipes/index.html.erb
<section >
<div class="contRL">
<h2 class="Rtitle">Recipes List</h2>
    <% if user_signed_in? %>
      <div class="actions">
        <%= link_to "Add New Recipe", new_recipe_path, class: "btn" %>
      </div>
    <% end %>
    </div>
    <div class="list">
      <% if @recipes.empty? %>
        <p>There are no recipes.</p>
      <% else %>
      <%= render @recipes %>
      <% end %>
    </div>


</section>

app/views/recipes/new.html.erb
<section class="new">
<h2>New Recipes</h2>
<div class="backToR">
  <%= link_to "Back to Recipes", recipes_path %>
</div>
<%= render "form", recipe: @recipe %>
</section>

app/views/recipes/public.html.erb
<div class="flex justify-center text-center p-8">
  <div class="w-[80%]">
    <p class="text-xl font-bold mb-2">Public Recipes</p>
    <ul class="flex flex-col items-center py-4">
      <% @public_recipes.each do |recipe| %>
        <li class="bg-white rounded-lg flex justify-between items-center w-[60%] my-2 py-2 px-4 border-2 border-gray-400 hover:shadow-xl">
          <div class="p-2">
            <div class="mb-2 text-green-600 hover:text-green-300 text-xl font-bold">
              <%= link_to recipe.name, recipe_path(recipe) %>
            </div>
            By: <span class="font-bold"><%= recipe.user.name %></span>
          </div>
          <div class="w-[80%] px-2 py-1 flex flex-col items-center gap-2">
            <div class="flex justify-between w-[50%]">
              <span>Total food items: </span>
              <span class="font-bold"><%= recipe.foods.length %></span>
            </div>
            <div class="flex justify-between w-[50%]">
              <span>Total price:</span>
              <span class="font-bold">$<%= @totals[recipe.id] %></span>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/recipes/show.html.erb
<section class="single">
  <article class="rec">
    <h2 class="h1">
    <%= @recipe.name %>
    </h2>
    <div class="public">
      <% if @recipe.public %>
      <div class="form-check form-switch">
        <label class="switch">
          <input type="checkbox">
          <span class="slider round"></span>
        </label>
      </div>
      <% else %>
      <div class="form-check form-switch">
        <label class="switch">
          <input type="checkbox" checked>
          <span class="slider round"></span>
        </label>
        </div>
      <% end %>
      
    </div>

    
    <div class="desc-rec">
    <ul>
      <li> Preparation Time: <%= @recipe.preparation_time %>  minutes 
      </li>
      <li> Cooking Time: <%= @recipe.cooking_time %> minutes
      </li>
    </ul>
      <h4 class="h4">Description</h4>

      <p class="border">
        <%= @recipe.description %>
      </p>
    </div>

    <div class="ingredientsbtn">
      <% if @recipe.user == current_user %>
        <%= link_to "Add Ingrdients", new_recipe_recipe_food_path(@recipe.id) %>
      <% end %>
    </div>
    <% if @recipe_foods.length > 0 %>
    <div class="table">
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Food</th>
            <th scope="col">Quantity</th>
            <th scope="col">Value</th> 
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>

          <% @recipe_foods.each do |recipe_food| %>
          <tr>
          <td><%= recipe_food.food.name %></td>
          <td><%= recipe_food.quantity %></td>
          <td><%= recipe_food.quantity * recipe_food.food.price %></td>
          <td>
          <% if current_user == recipe_food.recipe.user %>
                  <%= button_to 'Remove', recipe_recipe_food_path(@recipe, recipe_food), method: :delete, class: "bg-red-300 px-2 py-1 rounded-lg hover:bg-red-500 hover:text-white" %>
          <% end %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <% else %>
        <div>Add some ingrediant</div>
      <% end %>
    </div>
  </article>
  <button class="back">
    <%= link_to 'Back', recipes_path %>
  </button>
  
</section>