config/routes.rb
Rails.application.routes.draw do
  devise_for :users, sign_out_via: %i[get post]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :foods, except: %i[edit update]

  resources :recipes, except: %i[edit update] do
    resources :recipe_foods, only: %i[new create destroy]
  end

  # root to: 'foods#index'
  root to: 'recipes#index'
  get '/general_shopping_list', to: 'foods#general'
  get '/public_recipe', to: 'recipes#public'
  # post 'authenticate', to: 'authentication#authenticate'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  has_many :recipe_foods, dependent: :delete_all, foreign_key: 'food_id'

  validates :name, presence: true, length: { maximum: 250 }
  validates :quantity, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  private

  def food_list
    foods.includes([:user])
  end
end

app/controllers/food_controller.rb
class FoodsController < ApplicationController
  load_and_authorize_resource
  def index
    @user = User.find(params[:user_id])
    @foods = Food.includes(recipe_foods: [:user]).where(foods: { user_id: @user.id })
  end

  def show
    @food = Food.find(params[:id])
  end

  def new
    @food = Food.new
  end

  def create
    new_food = current_user.foods.new(food_params)
    new_food.quantity = 0
    new_food.price = 0

    respond_to do |format|
      format.html do
        if new_food.save
          redirect_to "/users/#{new_food.user_id}/foods/", notice: 'Post was successfully created.'
        else
          render :new, status: 'Error occured will creating post!'
        end
      end
    end
  end

  def destroy
    Food.delete(params[:id])
  end

  private

  def food_params
    params.require(:food).permit(:name, :text)
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = Food.all
  end

  def show
    @food = Food.find(params[:id])
  end

  def new
    @food = Food.new
  end

  def create
    new_food = current_user.foods.new(food_params)

    respond_to do |format|
      format.html do
        if new_food.save
          redirect_to '/foods/', notice: 'Post was successfully created.'
        else
          render :new, status: 'Error occured will creating post!'
        end
      end
    end
  end

  def destroy
    Food.delete(params[:id])
  end

  def general
    @foods = current_user.foods
    current_user.recipes.map do |recipe|
      recipe.recipe_foods.includes(:food).map do |recipe_food|
        food = recipe_food.food
        test = @foods.select { |f| f.name == food.name }[0]
        test.quantity = test.quantity - recipe_food.quantity
      end
    end
    @foods = @foods.select { |f| f.quantity.negative? }
    @foods.each { |f| f.quantity *= -1 }
    @total = 0
    @foods.each do |food|
      @total += (food.price * food.quantity)
    end
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/views/foods/general.html.erb
<div class="flex justify-center text-center p-8">
  <div class="w-[80%] shopping__list">
    <p class="font-bold text-xl">Shopping List</p>
    <div class="flex flex-wrap justify-around my-4">
      <div><span>Amount of food items to buy: </span><span class="font-bold">&nbsp;<%= @foods.length %></span></div>
      <div><span>Total value of food needed:</span><span class="font-bold">&nbsp;$<%= @total %></span></div>
    </div>
    <table class="w-full text-lg table-auto border-collapse">
      <thead>
        <tr>
          <th class="border border-slate-800 py-2">Food</th>
          <th class="border border-slate-800">Quantity</th>
          <th class="border border-slate-800">Price</th>
        </tr>
      </thead>
      <tbody>
        <% @foods.each do |food| %>
          <tr class="odd:bg-white even:bg-green-100">
            <td class="border border-slate-300 py-2"><%= food.name %></td>
            <td class="border border-slate-300"><%= food.quantity %></td>
            <td class="border border-slate-300">$<%= food.price * food.quantity %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/foods/index.html.erb
<div class="flex justify-center text-center p-8">
  <div class="w-[80%]">
    <div class="text-right mb-8"><%= link_to "Add Food", new_food_path, class: "py-2 px-4 rounded-lg bg-green-300 hover:bg-green-200 hover:shadow-xl" %></div>
    <table class="w-full text-lg table-auto border-collapse">
      <thead>
        <tr>
          <th class="border border-slate-800 py-2">Food</th>
          <th class="border border-slate-800">Quantity</th>
          <th class="border border-slate-800 w-44">Measurement Unit</th>
          <th class="border border-slate-800">Unit Price</th>
          <th class="border border-slate-800">Action</th>
        </tr>
      </thead>
      <tbody>
        <% @foods.each do |food| %>
          <tr class="odd:bg-white even:bg-green-100">
            <td class="border border-slate-300 py-2"><%= food.name %></td>
            <td class="border border-slate-300"><%= food.quantity %></td>
            <td class="border border-slate-300"><%= food.measurement_unit %></td>
            <td class="border border-slate-300">$<%= food.price %></td>
            <td class="border border-slate-300"><%= button_to "Delete", food_path(food.id), method: :delete, class: "bg-red-300 px-2 py-0 my-2 rounded-lg hover:bg-red-500 hover:text-white" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/foods/new.html.erb
<div class="createfood">
<h2>Create a Food</h2>
<%= form_with model: @food  do |form| %>
  <%= form.label :name, "Name" %>
  <%= form.text_field :name, placeholder: "Name", required: true%>
  <%= form.label :measurement_unit, "Measurement_unit" %>
  <%= form.text_area :measurement_unit, placeholder: "Measurement_unit...", required: true %>
  <%= form.label :price, "Price" %>
  <%= form.text_area :price, placeholder: "Price", required: true %>
  <%= form.label :quantity, "Quantity" %> 
  <%= form.text_area :quantity, placeholder: "Quantity", required: true %>
  <%= form.submit "Post" %>
<% end %>
</div>