config/routes.rb
Rails.application.routes.draw do
  devise_for :users, sign_out_via: %i[get post]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :foods, except: %i[edit update]

  resources :recipes, except: %i[edit update] do
    resources :recipe_foods, only: %i[new create destroy]
  end

  # root to: 'foods#index'
  root to: 'recipes#index'
  get '/general_shopping_list', to: 'foods#general'
  get '/public_recipe', to: 'recipes#public'
  # post 'authenticate', to: 'authentication#authenticate'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_navigation.html.erb
<nav class="nav__bar__main">
  <div class="nav__div">
    <%= form_with url: root_path, method: :get do %>
      <h1 class="cook__book">Cook Book</h1>
    <% end %>
    <% if current_user%>
      <%= form_with url: foods_path, method: :get do %>
        <button class="foods__btn">Foods</button>
      <% end %>
    <% end %>
     <% if current_user%>
      <%= form_with url: recipes_path, method: :get do %>
        <button class="recipes__btn">Recipes</button>
      <% end %>
    <% end %>
      <%= form_with url: public_recipe_path, method: :get do %>
        <button class="public__btn">Public Recipes</button>
      <% end %>
        <% if current_user%>
      <%= form_with url: general_shopping_list_path, method: :get do %>
        <button class="shop__btn">Shoping List</button>
      <% end %>
    <% end %>
  </div>
  <div class='flex sm:justify-between space-x-4'>
    <% unless current_user%>
    <%= form_with model: User.new, url: new_user_session_path, method: :get, class:'log' do %>
      <button class="signIn__btn"> Sign in</button>
    <% end %>
    <%= form_with model: User.new, url: new_user_registration_path, method: :get, class:'log' do %>
      <button class="signUp__btn">Sign up</button>
    <% end %>
  <% end %>
  <% if current_user %>
    <%=form_with model: User.new, url: destroy_user_session_path, data: { turbo_method: :delete },
class:'sign-out' do %> 
      <button class="signOut__btn">Sign out</button>
    <% end %>
    <span class='alert'>
     <p class="welcome">Welcome <%= current_user.name%></p>
    </span>
  <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CookBook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.tailwindcss.com" ></script>
  </head>

  <body>
  <%= render "layouts/navigation" %>
  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  <%= yield %>
  </body>
</html>